#define CDP_MODULUS_SIZE 96
#define CDP_GLOBALBROADCAST_TYPE 0x01
#define CDP_COINSIGNINGREQUEST_TYPE 0x02
#define CDP_SIGNEDCOIN_TYPE 0x03

#define BROADCAST_TIME_SEC 30
#define CSR_RSSI_THRESHOLD -85
#define BADGE_TX_POWER 1

#define UNSUBMITTED_COIN_PATH "/unsubmitted.lst"
#define MAX_NAME_LENGTH 50
#define MAX_JSON_SIZE 450
#define BASE64_MAX_SIZE 200
#define TXLOG_FLUSH_SEC 300

#define CACTUSCOINAPI_IP "172.16.42.1:5000"
#define MAX_NUM_BADGES 500
#define MAX_BADGE_ID_BYTES 6
