#define CDP_MODULUS_SIZE 96
#define CDP_GLOBALBROADCAST_TYPE 0x01
#define CDP_COINSIGNINGREQUEST_TYPE 0x02
#define CDP_SIGNEDCOIN_TYPE 0x03

#define BROADCAST_TIME_SEC 10
#define CSR_RSSI_THRESHOLD -70
